env: prod
namespace: dinopark-prod
domain_name: dinopark.k8s.sso.mozilla.com
pictures_domain_name: picture.api.sso.mozilla.com
assume_role: arn:aws:iam::320464205386:role/dino-park-fence-role-prod-us-west-2
dinopark_fence_replicas: 3
ingress_replicas: 5
router_replicas: 3
gatekeeper_replicas: 1
